In [1]:
from platform import python_version

print(python_version())

3.10.12

In [18]:
import pyreadr
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# constants
dataset_dir = "./datasets/TEP/"

In [13]:
def read_r_as_df(file_path):
    result = pyreadr.read_r(file_path) # also works for Rds
    return result[list(result.keys())[0]]

In [19]:
training_fault_free_df = read_r_as_df(f"{dataset_dir}/TEP_FaultFree_Training.RData")

In [15]:
test_falty_df = read_r_as_df(f"{dataset_dir}/TEP_Faulty_Testing.RData")

,faultNumber,simulationRun,sample,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
0,0,1.0,1,0.25171,3672.4,4466.3,9.5122,27.057,42.473,2705.6,...,54.494,24.527,59.710,22.357,40.149,40.074,47.955,47.300,42.100,15.345
1,0,1.0,2,0.25234,3642.2,4568.7,9.4145,26.999,42.586,2705.2,...,53.269,24.465,60.466,22.413,39.956,36.651,45.038,47.502,40.553,16.063
2,0,1.0,3,0.24840,3643.1,4507.5,9.2901,26.927,42.278,2703.5,...,54.000,24.860,60.642,22.199,40.074,41.868,44.553,47.479,41.341,20.452
3,0,1.0,4,0.25153,3628.3,4519.3,9.3347,26.999,42.330,2703.9,...,53.860,24.553,61.908,21.981,40.141,40.066,48.048,47.440,40.780,17.123
4,0,1.0,5,0.21763,3655.8,4571.0,9.3087,26.901,42.402,2707.7,...,53.307,21.775,61.891,22.412,37.696,38.295,44.678,47.530,41.089,18.681
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479995,0,500.0,956,0.26428,3671.5,4510.8,9.2852,27.141,42.297,2699.9,...,53.942,26.022,61.709,22.417,40.510,36.731,50.115,52.721,40.927,18.854
479996,0,500.0,957,0.25132,3573.4,4483.9,9.2872,26.604,42.311,2698.1,...,53.760,24.585,61.267,21.928,39.893,34.136,47.714,52.908,41.412,18.847
479997,0,500.0,958,0.25105,3622.6,4433.3,9.3998,26.707,41.936,2699.5,...,54.366,24.613,61.745,22.212,40.098,35.585,48.241,53.099,40.150,16.791
479998,0,500.0,959,0.24521,3660.5,4485.2,9.3885,26.936,42.639,2700.5,...,53.289,24.371,62.811,22.249,39.536,35.609,46.495,53.157,41.065,17.097
479999,0,500.0,960,0.24373,3652.1,4471.8,9.4359,27.309,42.015,2703.9,...,53.450,24.516,60.734,22.731,39.131,39.078,43.477,53.407,41.596,16.697